# -*- coding: utf-8 -*-
"""project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tpsmbndqVnaFgg8y9bPCqPioogGJ0nuX
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df=pd.read_csv("/content/diabetes_prediction_dataset.csv (1).zip")

df.head(20)

df.shape # .shape is an attribute to get dimensions.

df.info()

df.isnull().sum()

display(df.describe())

# We're identifying columns that hold text or categories, not just numbers.
categorical_cols = df.select_dtypes(include='object').columns

# Now we will look at each col.
for col in categorical_cols:
    print(f"\n inside data '{col}'? ")
    # value_counts() tells us how many times each unique category appears.
    display(df[col].value_counts())

    # And here's a bar chart to visually see the distribution of these categories.
    plt.figure(figsize=(8, 5))
    sns.countplot(x=col, data=df, palette='Set2')
    plt.title(f'How {col} is distributed among our participants')
    plt.xlabel(f'{col} Type')
    plt.ylabel('Number of People')
    plt.tight_layout()
    plt.show()

# These are the main numerical health-related measurements we want to inspect.
numerical_cols_for_dist = ['age', 'bmi', 'HbA1c_level', 'blood_glucose_level']

# We'll create several plots in one run to compare them easily.
plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols_for_dist):
    plt.subplot(2, 2, i + 1) # This arranges our plots into a 2x2 grid
    # A histplot shows the frequency of values and 'kde=True' adds a smooth line showing the density.
    sns.histplot(df[col], kde=True, bins=30, color='red')
    plt.title(f'How {col} is Spread Out')
    plt.xlabel(f'{col} Value')
    plt.ylabel('How Many People')
plt.tight_layout() # it helps to Makes sure titles and labels don't overlap.
plt.show()

# First, let's see the exact counts of how many '0' (no diabetes) and how many '1' (diabetes)are given in data.
print("\n How many people have diabetes vs. no diabetes?")
display(df['diabetes'].value_counts())

# Now, let's visualize this with a simple bar chart.
plt.figure(figsize=(5, 3))
sns.countplot(x='diabetes', data=df, palette='viridis') # 'countplot' is perfect for category counts.
plt.title('Who Has Diabetes (0: No, 1: Yes)')
plt.xlabel('Diabetes Status')
plt.ylabel('Number of Individuals')
plt.xticks(ticks=[0, 1], labels=['No Diabetes', 'Diabetes']) # Making the labels more readable.
plt.show()

# We'll use the same numerical columns as before to compare their values against the diabetes outcome.
numerical_cols_vs_diabetes = ['age', 'bmi', 'HbA1c_level', 'blood_glucose_level']

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols_vs_diabetes):
    plt.subplot(2, 2, i + 1) # Arranging these into a 2x2 grid
    # A 'boxplot' shows the distribution (median, quartiles, and outliers) for each group (diabetes=0 vs diabetes=1).
    sns.boxplot(x='diabetes', y=col, data=df, palette='coolwarm')
    plt.title(f'How {col} Varies with Diabetes Status')
    plt.xlabel('Diabetes (0: No, 1: Yes)')
    plt.ylabel(f'{col} Value')
plt.tight_layout()
plt.show()

# These are the pairs of numerical features we want to plot against each other.
plot_pairs = [
    ('age', 'bmi'),
    ('HbA1c_level', 'blood_glucose_level'),
    ('age', 'HbA1c_level'),
    ('bmi', 'HbA1c_level')
]

plt.figure(figsize=(18, 12))

for i, (x_col, y_col) in enumerate(plot_pairs):
    plt.subplot(2, 2, i + 1)
    #scatterplot visualizes two numerical variables. 'hue='diabetes'' colors points based on diabetes status.
    sns.scatterplot(x=x_col, y=y_col, hue='diabetes', data=df, alpha=0.6, palette='Set2')
    plt.title(f'{y_col} vs. {x_col}')
    plt.xlabel(x_col)
    plt.ylabel(y_col)
    plt.legend()
#orange dots shows people with diabetes.#green dot shows people with no diabetes.
plt.tight_layout()
plt.show()